#
# Makefile for the USB design example peripheral drivers.
#

O_TARGET	:= de.o

# Object file lists.

obj-$(CONFIG_USB_CY7C67200_300)			+= de1_dev.o
obj-$(CONFIG_USB_CY7C67200_300)			+= de3_dev.o
obj-$(CONFIG_USB_CY7C67200_300)			+= de4_dev.o

# Objects that export symbols.

include $(TOPDIR)/Rules.make

