#
#

# The target object and module list name.

O_TARGET	:= frvacpi.o

# Object file lists.
obj-y	:= facpi.o
obj-m	:= frvacpi.o
obj-n	:=
obj-	:=
#export-objs	:= facpi.o

#obj-$(CONFIG_FRV_ACPI_EMU)	+= frvacpi.o

#frvacpi-objs	:= facpi.o

# The global Rules.make.

include $(TOPDIR)/Rules.make

