#
# Makefile for the USB design example class drivers.
#

O_TARGET	:= de.o

# Object file lists.

obj-$(CONFIG_USB_CY7C67200_300)			+= de1_drv.o
obj-$(CONFIG_USB_CY7C67200_300)			+= de3_drv.o

# Objects that export symbols.

include $(TOPDIR)/Rules.make

