#
# Makefile for the Linux nios2-specific device drivers.
#

obj-$(CONFIG_PCI)		+= pci/
obj-$(CONFIG_FB_ALTERA)         += altfb.o
obj-$(CONFIG_SERIO_ALTPS2)	+= altps2.o
obj-$(CONFIG_I2C_NIOS2_GPIO)	+= i2c-gpio.o
obj-$(CONFIG_BLK_DEV_ALTCF)	+= altcf.o
obj-$(CONFIG_NIOS_SPI)		+= spi.o
