#
# Makefile for FRV-specific library files..
#

L_TARGET = lib.a
obj-y  = __ashldi3.o __lshrdi3.o __muldi3.o __ashrdi3.o __negdi2.o checksum.o memcpy.o memset.o \
	outsl_ns.o outsl_sw.o insl_ns.o insl_sw.o cache.o atomic-ops.o __div.o

include $(TOPDIR)/Rules.make
