#
# Makefile for the USB serial device drivers.
#

O_TARGET	:= usbdbi.o

# Object file lists.

obj-$(CONFIG_USB_CY7C67200_300)			+= usbd-bi.o
obj-$(CONFIG_USB_CY7C67200_300)			+= cy7c67200_300_pcd.o

include $(TOPDIR)/Rules.make

