
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 3.2.2 EDK_Cm.22
* DO NOT EDIT.
*
* Copyright (c) 2003 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

//#include <asm/xparameters.h>
#include "xsysace.h"

/*
* The configuration table for devices
*/

XSysAce_Config XSysAce_ConfigTable[] =
{
	{
		0,
		CONFIG_XILINX_SYSACE_0_BASEADDR
	}
};
