#
# Makefile for the linux microblaze specific parts of the memory manager
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

USE_STANDARD_AS_RULE := true

O_TARGET	:= mm.o

obj-y		:= init.o consistent.o memory.o
obj-m		:=
obj-n		:=
obj-		:=
export-objs	:= 

include $(TOPDIR)/Rules.make
