#
# Makefile for the 865x software big number operation
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definitions are now in the main makefile...

O_TARGET := rtl865x_dh.o
obj-y    := 	dh_gen.o \
	dh_check.o \
	dh_key.o \
	dh_lib.o \


include $(TOPDIR)/Rules.make
