/*******************************************************************
*
*     Author: Xilinx, Inc.
*     
*     
*     This program is free software; you can redistribute it and/or modify it
*     under the terms of the GNU General Public License as published by the
*     Free Software Foundation; either version 2 of the License, or (at your
*     option) any later version.
*     
*     
*     XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
*     COURTESY TO YOU. BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
*     ONE POSSIBLE IMPLEMENTATION OF THIS FEATURE, APPLICATION OR STANDARD,
*     XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION IS FREE
*     FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE FOR OBTAINING
*     ANY THIRD PARTY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
*     XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
*     THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO ANY
*     WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE FROM
*     CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY AND
*     FITNESS FOR A PARTICULAR PURPOSE.
*     
*     
*     Xilinx hardware products are not intended for use in life support
*     appliances, devices, or systems. Use in such applications is
*     expressly prohibited.
*     
*     
*     (c) Copyright 2002-2004 Xilinx Inc.
*     All rights reserved.
*     
*     
*     You should have received a copy of the GNU General Public License along
*     with this program; if not, write to the Free Software Foundation, Inc.,
*     675 Mass Ave, Cambridge, MA 02139, USA.
* 
* Description: Driver configuration
*
*******************************************************************/

#include <asm/autoconfig.h>
#include "xemac.h"

/*
* The configuration table for devices
*/

XEmac_Config XEmac_ConfigTable[] = {
	{
	 0,
	 CONFIG_XILINX_ETHERNET_0_BASEADDR,
	 CONFIG_XILINX_ETHERNET_0_BASEADDR,
	 CONFIG_XILINX_ETHERNET_0_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_0_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_0_MII_EXIST}
#ifdef CONFIG_XILINX_ETHERNET_1_INSTANCE
	,
	{
	 1,
	 CONFIG_XILINX_ETHERNET_1_BASEADDR,
	 CONFIG_XILINX_ETHERNET_1_BASEADDR,
	 CONFIG_XILINX_ETHERNET_1_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_1_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_1_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_2_INSTANCE
	,
	{
	 2,
	 CONFIG_XILINX_ETHERNET_2_BASEADDR,
	 CONFIG_XILINX_ETHERNET_2_BASEADDR,
	 CONFIG_XILINX_ETHERNET_2_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_2_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_2_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_3_INSTANCE
	,
	{
	 3,
	 CONFIG_XILINX_ETHERNET_3_BASEADDR,
	 CONFIG_XILINX_ETHERNET_3_BASEADDR,
	 CONFIG_XILINX_ETHERNET_3_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_3_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_3_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_4_INSTANCE
	,
	{
	 4,
	 CONFIG_XILINX_ETHERNET_4_BASEADDR,
	 CONFIG_XILINX_ETHERNET_4_BASEADDR,
	 CONFIG_XILINX_ETHERNET_4_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_4_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_4_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_5_INSTANCE
	,
	{
	 5,
	 CONFIG_XILINX_ETHERNET_5_BASEADDR,
	 CONFIG_XILINX_ETHERNET_5_BASEADDR,
	 CONFIG_XILINX_ETHERNET_5_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_5_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_5_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_6_INSTANCE
	,
	{
	 6,
	 CONFIG_XILINX_ETHERNET_6_BASEADDR,
	 CONFIG_XILINX_ETHERNET_6_BASEADDR,
	 CONFIG_XILINX_ETHERNET_6_ERR_COUNT_EXIST,
	 CONFIG_XILINX_ETHERNET_6_DMA_PRESENT,
	 CONFIG_XILINX_ETHERNET_6_MII_EXIST}
#endif
#ifdef CONFIG_XILINX_ETHERNET_7_INSTANCE
	#error Edit this file to add more devices.
#endif
};
