#ifndef XHWICAP_IOCTL_H
#define XHWICAP_IOCTL_H

#include <linux/ioctl.h>

#define XHWICAP_IOC_MAGIC 'i'

#define XHWICAP_IOCCMDDESYNC _IO(XHWICAP_IOC_MAGIC, 1)
#define XHWICAP_IOCCMDCAPTURE _IO(XHWICAP_IOC_MAGIC, 2)
#define XHWICAP_IOCGETINST _IO(XHWICAP_IOC_MAGIC, 3)

#endif
